//~false
//A small library for two-coloring graphs
package main

type node struct{
	neighbors[] node;
	color int;
	visited bool;
}

type graph struct{
	nodes[] node;
	directed bool;
}


func twoColor(myNode node) bool{
	myNode.visited = true;
	var badNodes bool = false;
	for i:= 0; i < len(myNode.neighbors); i++ {
		if(myNode.neighbors[i].color == myNode.color){
			return false;
		} else if (!(myNode.neighbors[i].visited)) {
			if(myNode.color == 1){
				myNode.neighbors[i].color = 2;
			} else {
				myNode.neighbors[i].color = 1;
			}
			badNodes = (badNodes || twoColor(myNode.neighbors[i]));
		}
	}
	return badNodes;
}

func twoColorable(myGraph graph) bool{
	if(len(myGraph.nodes) == 0){
		print("Empty graph!\n");
		return true;
	}
	var startNode node;
	startNode = myGraph.nodes[0];
	startNode.color = 1;
	return twoColor(startNode);
	
	
}

func main() {
	var triangleGraph graph;
	var node0 node;
	var node0a node;
	var node0b node;
	var node1 node;
	var node1a node;
	var node1b node;
	var node2 node;
	var node2a node;
	var node2b node;
	var node3 node;
	var node3a node;
	var node3b node;
	var node4 node;
	var node4a node;
	var node4b node;
	var node5 node;
	var node5a node;
	var node5b node;
	var node6 node;
	var node6a node;
	var node6b node;
	var node7 node;
	var node7a node;
	var node7b node;
	var node8 node;
	var node8a node;
	var node8b node;
	var node9 node;
	var node9a node;
	var node9b node;
	var node10 node;
	var node10a node;
	var node10b node;
	var node11 node;
	var node11a node;
	var node11b node;
	var node12 node;
	var node12a node;
	var node12b node;
	var node13 node;
	var node13a node;
	var node13b node;
	var node14 node;
	var node14a node;
	var node14b node;
	var node15 node;
	var node15a node;
	var node15b node;
	var node16 node;
	var node16a node;
	var node16b node;
	var node17 node;
	var node17a node;
	var node17b node;
	var node18 node;
	var node18a node;
	var node18b node;
	var node19 node;
	var node19a node;
	var node19b node;
	var node20 node;
	var node20a node;
	var node20b node;
	var node21 node;
	var node21a node;
	var node21b node;
	var node22 node;
	var node22a node;
	var node22b node;
	var node23 node;
	var node23a node;
	var node23b node;
	var node24 node;
	var node24a node;
	var node24b node;
	var node25 node;
	var node25a node;
	var node25b node;
	var node26 node;
	var node26a node;
	var node26b node;
	var node27 node;
	var node27a node;
	var node27b node;
	var node28 node;
	var node28a node;
	var node28b node;
	var node29 node;
	var node29a node;
	var node29b node;
	var node30 node;
	var node30a node;
	var node30b node;
	var node31 node;
	var node31a node;
	var node31b node;
	var node32 node;
	var node32a node;
	var node32b node;
	var node33 node;
	var node33a node;
	var node33b node;
	var node34 node;
	var node34a node;
	var node34b node;
	var node35 node;
	var node35a node;
	var node35b node;
	var node36 node;
	var node36a node;
	var node36b node;
	var node37 node;
	var node37a node;
	var node37b node;
	var node38 node;
	var node38a node;
	var node38b node;
	var node39 node;
	var node39a node;
	var node39b node;
	var node40 node;
	var node40a node;
	var node40b node;
	var node41 node;
	var node41a node;
	var node41b node;
	var node42 node;
	var node42a node;
	var node42b node;
	var node43 node;
	var node43a node;
	var node43b node;
	var node44 node;
	var node44a node;
	var node44b node;
	var node45 node;
	var node45a node;
	var node45b node;
	var node46 node;
	var node46a node;
	var node46b node;
	var node47 node;
	var node47a node;
	var node47b node;
	var node48 node;
	var node48a node;
	var node48b node;
	var node49 node;
	var node49a node;
	var node49b node;
	var node50 node;
	var node50a node;
	var node50b node;
	var node51 node;
	var node51a node;
	var node51b node;
	var node52 node;
	var node52a node;
	var node52b node;
	var node53 node;
	var node53a node;
	var node53b node;
	var node54 node;
	var node54a node;
	var node54b node;
	var node55 node;
	var node55a node;
	var node55b node;
	var node56 node;
	var node56a node;
	var node56b node;
	var node57 node;
	var node57a node;
	var node57b node;
	var node58 node;
	var node58a node;
	var node58b node;
	var node59 node;
	var node59a node;
	var node59b node;
	var node60 node;
	var node60a node;
	var node60b node;
	var node61 node;
	var node61a node;
	var node61b node;
	var node62 node;
	var node62a node;
	var node62b node;
	var node63 node;
	var node63a node;
	var node63b node;
	var node64 node;
	var node64a node;
	var node64b node;
	var node65 node;
	var node65a node;
	var node65b node;
	var node66 node;
	var node66a node;
	var node66b node;
	var node67 node;
	var node67a node;
	var node67b node;
	var node68 node;
	var node68a node;
	var node68b node;
	var node69 node;
	var node69a node;
	var node69b node;
	var node70 node;
	var node70a node;
	var node70b node;
	var node71 node;
	var node71a node;
	var node71b node;
	var node72 node;
	var node72a node;
	var node72b node;
	var node73 node;
	var node73a node;
	var node73b node;
	var node74 node;
	var node74a node;
	var node74b node;
	var node75 node;
	var node75a node;
	var node75b node;
	var node76 node;
	var node76a node;
	var node76b node;
	var node77 node;
	var node77a node;
	var node77b node;
	var node78 node;
	var node78a node;
	var node78b node;
	var node79 node;
	var node79a node;
	var node79b node;
	var node80 node;
	var node80a node;
	var node80b node;
	var node81 node;
	var node81a node;
	var node81b node;
	var node82 node;
	var node82a node;
	var node82b node;
	var node83 node;
	var node83a node;
	var node83b node;
	var node84 node;
	var node84a node;
	var node84b node;
	var node85 node;
	var node85a node;
	var node85b node;
	var node86 node;
	var node86a node;
	var node86b node;
	var node87 node;
	var node87a node;
	var node87b node;
	var node88 node;
	var node88a node;
	var node88b node;
	var node89 node;
	var node89a node;
	var node89b node;
	var node90 node;
	var node90a node;
	var node90b node;
	var node91 node;
	var node91a node;
	var node91b node;
	var node92 node;
	var node92a node;
	var node92b node;
	var node93 node;
	var node93a node;
	var node93b node;
	var node94 node;
	var node94a node;
	var node94b node;
	var node95 node;
	var node95a node;
	var node95b node;
	var node96 node;
	var node96a node;
	var node96b node;
	var node97 node;
	var node97a node;
	var node97b node;
	var node98 node;
	var node98a node;
	var node98b node;
	var node99 node;
	var node99a node;
	var node99b node;
	var node100 node;
	var node100a node;
	var node100b node;
	var node101 node;
	var node101a node;
	var node101b node;
	var node102 node;
	var node102a node;
	var node102b node;
	var node103 node;
	var node103a node;
	var node103b node;
	var node104 node;
	var node104a node;
	var node104b node;
	var node105 node;
	var node105a node;
	var node105b node;
	var node106 node;
	var node106a node;
	var node106b node;
	var node107 node;
	var node107a node;
	var node107b node;
	var node108 node;
	var node108a node;
	var node108b node;
	var node109 node;
	var node109a node;
	var node109b node;
	var node110 node;
	var node110a node;
	var node110b node;
	var node111 node;
	var node111a node;
	var node111b node;
	var node112 node;
	var node112a node;
	var node112b node;
	var node113 node;
	var node113a node;
	var node113b node;
	var node114 node;
	var node114a node;
	var node114b node;
	var node115 node;
	var node115a node;
	var node115b node;
	var node116 node;
	var node116a node;
	var node116b node;
	var node117 node;
	var node117a node;
	var node117b node;
	var node118 node;
	var node118a node;
	var node118b node;
	var node119 node;
	var node119a node;
	var node119b node;
	var node120 node;
	var node120a node;
	var node120b node;
	var node121 node;
	var node121a node;
	var node121b node;
	var node122 node;
	var node122a node;
	var node122b node;
	var node123 node;
	var node123a node;
	var node123b node;
	var node124 node;
	var node124a node;
	var node124b node;
	var node125 node;
	var node125a node;
	var node125b node;
	var node126 node;
	var node126a node;
	var node126b node;
	var node127 node;
	var node127a node;
	var node127b node;
	var node128 node;
	var node128a node;
	var node128b node;
	var node129 node;
	var node129a node;
	var node129b node;
	var node130 node;
	var node130a node;
	var node130b node;
	var node131 node;
	var node131a node;
	var node131b node;
	var node132 node;
	var node132a node;
	var node132b node;
	var node133 node;
	var node133a node;
	var node133b node;
	var node134 node;
	var node134a node;
	var node134b node;
	var node135 node;
	var node135a node;
	var node135b node;
	var node136 node;
	var node136a node;
	var node136b node;
	var node137 node;
	var node137a node;
	var node137b node;
	var node138 node;
	var node138a node;
	var node138b node;
	var node139 node;
	var node139a node;
	var node139b node;
	var node140 node;
	var node140a node;
	var node140b node;
	var node141 node;
	var node141a node;
	var node141b node;
	var node142 node;
	var node142a node;
	var node142b node;
	var node143 node;
	var node143a node;
	var node143b node;
	var node144 node;
	var node144a node;
	var node144b node;
	var node145 node;
	var node145a node;
	var node145b node;
	var node146 node;
	var node146a node;
	var node146b node;
	var node147 node;
	var node147a node;
	var node147b node;
	var node148 node;
	var node148a node;
	var node148b node;
	var node149 node;
	var node149a node;
	var node149b node;
	var node150 node;
	var node150a node;
	var node150b node;
	var node151 node;
	var node151a node;
	var node151b node;
	var node152 node;
	var node152a node;
	var node152b node;
	var node153 node;
	var node153a node;
	var node153b node;
	var node154 node;
	var node154a node;
	var node154b node;
	var node155 node;
	var node155a node;
	var node155b node;
	var node156 node;
	var node156a node;
	var node156b node;
	var node157 node;
	var node157a node;
	var node157b node;
	var node158 node;
	var node158a node;
	var node158b node;
	var node159 node;
	var node159a node;
	var node159b node;
	var node160 node;
	var node160a node;
	var node160b node;
	var node161 node;
	var node161a node;
	var node161b node;
	var node162 node;
	var node162a node;
	var node162b node;
	var node163 node;
	var node163a node;
	var node163b node;
	var node164 node;
	var node164a node;
	var node164b node;
	var node165 node;
	var node165a node;
	var node165b node;
	var node166 node;
	var node166a node;
	var node166b node;
	var node167 node;
	var node167a node;
	var node167b node;
	var node168 node;
	var node168a node;
	var node168b node;
	var node169 node;
	var node169a node;
	var node169b node;
	var node170 node;
	var node170a node;
	var node170b node;
	var node171 node;
	var node171a node;
	var node171b node;
	var node172 node;
	var node172a node;
	var node172b node;
	var node173 node;
	var node173a node;
	var node173b node;
	var node174 node;
	var node174a node;
	var node174b node;
	var node175 node;
	var node175a node;
	var node175b node;
	var node176 node;
	var node176a node;
	var node176b node;
	var node177 node;
	var node177a node;
	var node177b node;
	var node178 node;
	var node178a node;
	var node178b node;
	var node179 node;
	var node179a node;
	var node179b node;
	var node180 node;
	var node180a node;
	var node180b node;
	var node181 node;
	var node181a node;
	var node181b node;
	var node182 node;
	var node182a node;
	var node182b node;
	var node183 node;
	var node183a node;
	var node183b node;
	var node184 node;
	var node184a node;
	var node184b node;
	var node185 node;
	var node185a node;
	var node185b node;
	var node186 node;
	var node186a node;
	var node186b node;
	var node187 node;
	var node187a node;
	var node187b node;
	var node188 node;
	var node188a node;
	var node188b node;
	var node189 node;
	var node189a node;
	var node189b node;
	var node190 node;
	var node190a node;
	var node190b node;
	var node191 node;
	var node191a node;
	var node191b node;
	var node192 node;
	var node192a node;
	var node192b node;
	var node193 node;
	var node193a node;
	var node193b node;
	var node194 node;
	var node194a node;
	var node194b node;
	var node195 node;
	var node195a node;
	var node195b node;
	var node196 node;
	var node196a node;
	var node196b node;
	var node197 node;
	var node197a node;
	var node197b node;
	var node198 node;
	var node198a node;
	var node198b node;
	var node199 node;
	var node199a node;
	var node199b node;
	node0.neighbors = append(node0.neighbors, node0a);
	node0.neighbors = append(node0.neighbors, node0b);
	node0.neighbors = append(node0.neighbors, node1);
	node1.neighbors = append(node1.neighbors, node1a);
	node1.neighbors = append(node1.neighbors, node1b);
	node1.neighbors = append(node1.neighbors, node2);
	node2.neighbors = append(node2.neighbors, node2a);
	node2.neighbors = append(node2.neighbors, node2b);
	node2.neighbors = append(node2.neighbors, node3);
	node3.neighbors = append(node3.neighbors, node3a);
	node3.neighbors = append(node3.neighbors, node3b);
	node3.neighbors = append(node3.neighbors, node4);
	node4.neighbors = append(node4.neighbors, node4a);
	node4.neighbors = append(node4.neighbors, node4b);
	node4.neighbors = append(node4.neighbors, node5);
	node5.neighbors = append(node5.neighbors, node5a);
	node5.neighbors = append(node5.neighbors, node5b);
	node5.neighbors = append(node5.neighbors, node6);
	node6.neighbors = append(node6.neighbors, node6a);
	node6.neighbors = append(node6.neighbors, node6b);
	node6.neighbors = append(node6.neighbors, node7);
	node7.neighbors = append(node7.neighbors, node7a);
	node7.neighbors = append(node7.neighbors, node7b);
	node7.neighbors = append(node7.neighbors, node8);
	node8.neighbors = append(node8.neighbors, node8a);
	node8.neighbors = append(node8.neighbors, node8b);
	node8.neighbors = append(node8.neighbors, node9);
	node9.neighbors = append(node9.neighbors, node9a);
	node9.neighbors = append(node9.neighbors, node9b);
	node9.neighbors = append(node9.neighbors, node10);
	node10.neighbors = append(node10.neighbors, node10a);
	node10.neighbors = append(node10.neighbors, node10b);
	node10.neighbors = append(node10.neighbors, node11);
	node11.neighbors = append(node11.neighbors, node11a);
	node11.neighbors = append(node11.neighbors, node11b);
	node11.neighbors = append(node11.neighbors, node12);
	node12.neighbors = append(node12.neighbors, node12a);
	node12.neighbors = append(node12.neighbors, node12b);
	node12.neighbors = append(node12.neighbors, node13);
	node13.neighbors = append(node13.neighbors, node13a);
	node13.neighbors = append(node13.neighbors, node13b);
	node13.neighbors = append(node13.neighbors, node14);
	node14.neighbors = append(node14.neighbors, node14a);
	node14.neighbors = append(node14.neighbors, node14b);
	node14.neighbors = append(node14.neighbors, node15);
	node15.neighbors = append(node15.neighbors, node15a);
	node15.neighbors = append(node15.neighbors, node15b);
	node15.neighbors = append(node15.neighbors, node16);
	node16.neighbors = append(node16.neighbors, node16a);
	node16.neighbors = append(node16.neighbors, node16b);
	node16.neighbors = append(node16.neighbors, node17);
	node17.neighbors = append(node17.neighbors, node17a);
	node17.neighbors = append(node17.neighbors, node17b);
	node17.neighbors = append(node17.neighbors, node18);
	node18.neighbors = append(node18.neighbors, node18a);
	node18.neighbors = append(node18.neighbors, node18b);
	node18.neighbors = append(node18.neighbors, node19);
	node19.neighbors = append(node19.neighbors, node19a);
	node19.neighbors = append(node19.neighbors, node19b);
	node19.neighbors = append(node19.neighbors, node20);
	node20.neighbors = append(node20.neighbors, node20a);
	node20.neighbors = append(node20.neighbors, node20b);
	node20.neighbors = append(node20.neighbors, node21);
	node21.neighbors = append(node21.neighbors, node21a);
	node21.neighbors = append(node21.neighbors, node21b);
	node21.neighbors = append(node21.neighbors, node22);
	node22.neighbors = append(node22.neighbors, node22a);
	node22.neighbors = append(node22.neighbors, node22b);
	node22.neighbors = append(node22.neighbors, node23);
	node23.neighbors = append(node23.neighbors, node23a);
	node23.neighbors = append(node23.neighbors, node23b);
	node23.neighbors = append(node23.neighbors, node24);
	node24.neighbors = append(node24.neighbors, node24a);
	node24.neighbors = append(node24.neighbors, node24b);
	node24.neighbors = append(node24.neighbors, node25);
	node25.neighbors = append(node25.neighbors, node25a);
	node25.neighbors = append(node25.neighbors, node25b);
	node25.neighbors = append(node25.neighbors, node26);
	node26.neighbors = append(node26.neighbors, node26a);
	node26.neighbors = append(node26.neighbors, node26b);
	node26.neighbors = append(node26.neighbors, node27);
	node27.neighbors = append(node27.neighbors, node27a);
	node27.neighbors = append(node27.neighbors, node27b);
	node27.neighbors = append(node27.neighbors, node28);
	node28.neighbors = append(node28.neighbors, node28a);
	node28.neighbors = append(node28.neighbors, node28b);
	node28.neighbors = append(node28.neighbors, node29);
	node29.neighbors = append(node29.neighbors, node29a);
	node29.neighbors = append(node29.neighbors, node29b);
	node29.neighbors = append(node29.neighbors, node30);
	node30.neighbors = append(node30.neighbors, node30a);
	node30.neighbors = append(node30.neighbors, node30b);
	node30.neighbors = append(node30.neighbors, node31);
	node31.neighbors = append(node31.neighbors, node31a);
	node31.neighbors = append(node31.neighbors, node31b);
	node31.neighbors = append(node31.neighbors, node32);
	node32.neighbors = append(node32.neighbors, node32a);
	node32.neighbors = append(node32.neighbors, node32b);
	node32.neighbors = append(node32.neighbors, node33);
	node33.neighbors = append(node33.neighbors, node33a);
	node33.neighbors = append(node33.neighbors, node33b);
	node33.neighbors = append(node33.neighbors, node34);
	node34.neighbors = append(node34.neighbors, node34a);
	node34.neighbors = append(node34.neighbors, node34b);
	node34.neighbors = append(node34.neighbors, node35);
	node35.neighbors = append(node35.neighbors, node35a);
	node35.neighbors = append(node35.neighbors, node35b);
	node35.neighbors = append(node35.neighbors, node36);
	node36.neighbors = append(node36.neighbors, node36a);
	node36.neighbors = append(node36.neighbors, node36b);
	node36.neighbors = append(node36.neighbors, node37);
	node37.neighbors = append(node37.neighbors, node37a);
	node37.neighbors = append(node37.neighbors, node37b);
	node37.neighbors = append(node37.neighbors, node38);
	node38.neighbors = append(node38.neighbors, node38a);
	node38.neighbors = append(node38.neighbors, node38b);
	node38.neighbors = append(node38.neighbors, node39);
	node39.neighbors = append(node39.neighbors, node39a);
	node39.neighbors = append(node39.neighbors, node39b);
	node39.neighbors = append(node39.neighbors, node40);
	node40.neighbors = append(node40.neighbors, node40a);
	node40.neighbors = append(node40.neighbors, node40b);
	node40.neighbors = append(node40.neighbors, node41);
	node41.neighbors = append(node41.neighbors, node41a);
	node41.neighbors = append(node41.neighbors, node41b);
	node41.neighbors = append(node41.neighbors, node42);
	node42.neighbors = append(node42.neighbors, node42a);
	node42.neighbors = append(node42.neighbors, node42b);
	node42.neighbors = append(node42.neighbors, node43);
	node43.neighbors = append(node43.neighbors, node43a);
	node43.neighbors = append(node43.neighbors, node43b);
	node43.neighbors = append(node43.neighbors, node44);
	node44.neighbors = append(node44.neighbors, node44a);
	node44.neighbors = append(node44.neighbors, node44b);
	node44.neighbors = append(node44.neighbors, node45);
	node45.neighbors = append(node45.neighbors, node45a);
	node45.neighbors = append(node45.neighbors, node45b);
	node45.neighbors = append(node45.neighbors, node46);
	node46.neighbors = append(node46.neighbors, node46a);
	node46.neighbors = append(node46.neighbors, node46b);
	node46.neighbors = append(node46.neighbors, node47);
	node47.neighbors = append(node47.neighbors, node47a);
	node47.neighbors = append(node47.neighbors, node47b);
	node47.neighbors = append(node47.neighbors, node48);
	node48.neighbors = append(node48.neighbors, node48a);
	node48.neighbors = append(node48.neighbors, node48b);
	node48.neighbors = append(node48.neighbors, node49);
	node49.neighbors = append(node49.neighbors, node49a);
	node49.neighbors = append(node49.neighbors, node49b);
	node49.neighbors = append(node49.neighbors, node50);
	node50.neighbors = append(node50.neighbors, node50a);
	node50.neighbors = append(node50.neighbors, node50b);
	node50.neighbors = append(node50.neighbors, node51);
	node51.neighbors = append(node51.neighbors, node51a);
	node51.neighbors = append(node51.neighbors, node51b);
	node51.neighbors = append(node51.neighbors, node52);
	node52.neighbors = append(node52.neighbors, node52a);
	node52.neighbors = append(node52.neighbors, node52b);
	node52.neighbors = append(node52.neighbors, node53);
	node53.neighbors = append(node53.neighbors, node53a);
	node53.neighbors = append(node53.neighbors, node53b);
	node53.neighbors = append(node53.neighbors, node54);
	node54.neighbors = append(node54.neighbors, node54a);
	node54.neighbors = append(node54.neighbors, node54b);
	node54.neighbors = append(node54.neighbors, node55);
	node55.neighbors = append(node55.neighbors, node55a);
	node55.neighbors = append(node55.neighbors, node55b);
	node55.neighbors = append(node55.neighbors, node56);
	node56.neighbors = append(node56.neighbors, node56a);
	node56.neighbors = append(node56.neighbors, node56b);
	node56.neighbors = append(node56.neighbors, node57);
	node57.neighbors = append(node57.neighbors, node57a);
	node57.neighbors = append(node57.neighbors, node57b);
	node57.neighbors = append(node57.neighbors, node58);
	node58.neighbors = append(node58.neighbors, node58a);
	node58.neighbors = append(node58.neighbors, node58b);
	node58.neighbors = append(node58.neighbors, node59);
	node59.neighbors = append(node59.neighbors, node59a);
	node59.neighbors = append(node59.neighbors, node59b);
	node59.neighbors = append(node59.neighbors, node60);
	node60.neighbors = append(node60.neighbors, node60a);
	node60.neighbors = append(node60.neighbors, node60b);
	node60.neighbors = append(node60.neighbors, node61);
	node61.neighbors = append(node61.neighbors, node61a);
	node61.neighbors = append(node61.neighbors, node61b);
	node61.neighbors = append(node61.neighbors, node62);
	node62.neighbors = append(node62.neighbors, node62a);
	node62.neighbors = append(node62.neighbors, node62b);
	node62.neighbors = append(node62.neighbors, node63);
	node63.neighbors = append(node63.neighbors, node63a);
	node63.neighbors = append(node63.neighbors, node63b);
	node63.neighbors = append(node63.neighbors, node64);
	node64.neighbors = append(node64.neighbors, node64a);
	node64.neighbors = append(node64.neighbors, node64b);
	node64.neighbors = append(node64.neighbors, node65);
	node65.neighbors = append(node65.neighbors, node65a);
	node65.neighbors = append(node65.neighbors, node65b);
	node65.neighbors = append(node65.neighbors, node66);
	node66.neighbors = append(node66.neighbors, node66a);
	node66.neighbors = append(node66.neighbors, node66b);
	node66.neighbors = append(node66.neighbors, node67);
	node67.neighbors = append(node67.neighbors, node67a);
	node67.neighbors = append(node67.neighbors, node67b);
	node67.neighbors = append(node67.neighbors, node68);
	node68.neighbors = append(node68.neighbors, node68a);
	node68.neighbors = append(node68.neighbors, node68b);
	node68.neighbors = append(node68.neighbors, node69);
	node69.neighbors = append(node69.neighbors, node69a);
	node69.neighbors = append(node69.neighbors, node69b);
	node69.neighbors = append(node69.neighbors, node70);
	node70.neighbors = append(node70.neighbors, node70a);
	node70.neighbors = append(node70.neighbors, node70b);
	node70.neighbors = append(node70.neighbors, node71);
	node71.neighbors = append(node71.neighbors, node71a);
	node71.neighbors = append(node71.neighbors, node71b);
	node71.neighbors = append(node71.neighbors, node72);
	node72.neighbors = append(node72.neighbors, node72a);
	node72.neighbors = append(node72.neighbors, node72b);
	node72.neighbors = append(node72.neighbors, node73);
	node73.neighbors = append(node73.neighbors, node73a);
	node73.neighbors = append(node73.neighbors, node73b);
	node73.neighbors = append(node73.neighbors, node74);
	node74.neighbors = append(node74.neighbors, node74a);
	node74.neighbors = append(node74.neighbors, node74b);
	node74.neighbors = append(node74.neighbors, node75);
	node75.neighbors = append(node75.neighbors, node75a);
	node75.neighbors = append(node75.neighbors, node75b);
	node75.neighbors = append(node75.neighbors, node76);
	node76.neighbors = append(node76.neighbors, node76a);
	node76.neighbors = append(node76.neighbors, node76b);
	node76.neighbors = append(node76.neighbors, node77);
	node77.neighbors = append(node77.neighbors, node77a);
	node77.neighbors = append(node77.neighbors, node77b);
	node77.neighbors = append(node77.neighbors, node78);
	node78.neighbors = append(node78.neighbors, node78a);
	node78.neighbors = append(node78.neighbors, node78b);
	node78.neighbors = append(node78.neighbors, node79);
	node79.neighbors = append(node79.neighbors, node79a);
	node79.neighbors = append(node79.neighbors, node79b);
	node79.neighbors = append(node79.neighbors, node80);
	node80.neighbors = append(node80.neighbors, node80a);
	node80.neighbors = append(node80.neighbors, node80b);
	node80.neighbors = append(node80.neighbors, node81);
	node81.neighbors = append(node81.neighbors, node81a);
	node81.neighbors = append(node81.neighbors, node81b);
	node81.neighbors = append(node81.neighbors, node82);
	node82.neighbors = append(node82.neighbors, node82a);
	node82.neighbors = append(node82.neighbors, node82b);
	node82.neighbors = append(node82.neighbors, node83);
	node83.neighbors = append(node83.neighbors, node83a);
	node83.neighbors = append(node83.neighbors, node83b);
	node83.neighbors = append(node83.neighbors, node84);
	node84.neighbors = append(node84.neighbors, node84a);
	node84.neighbors = append(node84.neighbors, node84b);
	node84.neighbors = append(node84.neighbors, node85);
	node85.neighbors = append(node85.neighbors, node85a);
	node85.neighbors = append(node85.neighbors, node85b);
	node85.neighbors = append(node85.neighbors, node86);
	node86.neighbors = append(node86.neighbors, node86a);
	node86.neighbors = append(node86.neighbors, node86b);
	node86.neighbors = append(node86.neighbors, node87);
	node87.neighbors = append(node87.neighbors, node87a);
	node87.neighbors = append(node87.neighbors, node87b);
	node87.neighbors = append(node87.neighbors, node88);
	node88.neighbors = append(node88.neighbors, node88a);
	node88.neighbors = append(node88.neighbors, node88b);
	node88.neighbors = append(node88.neighbors, node89);
	node89.neighbors = append(node89.neighbors, node89a);
	node89.neighbors = append(node89.neighbors, node89b);
	node89.neighbors = append(node89.neighbors, node90);
	node90.neighbors = append(node90.neighbors, node90a);
	node90.neighbors = append(node90.neighbors, node90b);
	node90.neighbors = append(node90.neighbors, node91);
	node91.neighbors = append(node91.neighbors, node91a);
	node91.neighbors = append(node91.neighbors, node91b);
	node91.neighbors = append(node91.neighbors, node92);
	node92.neighbors = append(node92.neighbors, node92a);
	node92.neighbors = append(node92.neighbors, node92b);
	node92.neighbors = append(node92.neighbors, node93);
	node93.neighbors = append(node93.neighbors, node93a);
	node93.neighbors = append(node93.neighbors, node93b);
	node93.neighbors = append(node93.neighbors, node94);
	node94.neighbors = append(node94.neighbors, node94a);
	node94.neighbors = append(node94.neighbors, node94b);
	node94.neighbors = append(node94.neighbors, node95);
	node95.neighbors = append(node95.neighbors, node95a);
	node95.neighbors = append(node95.neighbors, node95b);
	node95.neighbors = append(node95.neighbors, node96);
	node96.neighbors = append(node96.neighbors, node96a);
	node96.neighbors = append(node96.neighbors, node96b);
	node96.neighbors = append(node96.neighbors, node97);
	node97.neighbors = append(node97.neighbors, node97a);
	node97.neighbors = append(node97.neighbors, node97b);
	node97.neighbors = append(node97.neighbors, node98);
	node98.neighbors = append(node98.neighbors, node98a);
	node98.neighbors = append(node98.neighbors, node98b);
	node98.neighbors = append(node98.neighbors, node99);
	node99.neighbors = append(node99.neighbors, node99a);
	node99.neighbors = append(node99.neighbors, node99b);
	node99.neighbors = append(node99.neighbors, node100);
	node100.neighbors = append(node100.neighbors, node100a);
	node100.neighbors = append(node100.neighbors, node100b);
	node100.neighbors = append(node100.neighbors, node101);
	node101.neighbors = append(node101.neighbors, node101a);
	node101.neighbors = append(node101.neighbors, node101b);
	node101.neighbors = append(node101.neighbors, node102);
	node102.neighbors = append(node102.neighbors, node102a);
	node102.neighbors = append(node102.neighbors, node102b);
	node102.neighbors = append(node102.neighbors, node103);
	node103.neighbors = append(node103.neighbors, node103a);
	node103.neighbors = append(node103.neighbors, node103b);
	node103.neighbors = append(node103.neighbors, node104);
	node104.neighbors = append(node104.neighbors, node104a);
	node104.neighbors = append(node104.neighbors, node104b);
	node104.neighbors = append(node104.neighbors, node105);
	node105.neighbors = append(node105.neighbors, node105a);
	node105.neighbors = append(node105.neighbors, node105b);
	node105.neighbors = append(node105.neighbors, node106);
	node106.neighbors = append(node106.neighbors, node106a);
	node106.neighbors = append(node106.neighbors, node106b);
	node106.neighbors = append(node106.neighbors, node107);
	node107.neighbors = append(node107.neighbors, node107a);
	node107.neighbors = append(node107.neighbors, node107b);
	node107.neighbors = append(node107.neighbors, node108);
	node108.neighbors = append(node108.neighbors, node108a);
	node108.neighbors = append(node108.neighbors, node108b);
	node108.neighbors = append(node108.neighbors, node109);
	node109.neighbors = append(node109.neighbors, node109a);
	node109.neighbors = append(node109.neighbors, node109b);
	node109.neighbors = append(node109.neighbors, node110);
	node110.neighbors = append(node110.neighbors, node110a);
	node110.neighbors = append(node110.neighbors, node110b);
	node110.neighbors = append(node110.neighbors, node111);
	node111.neighbors = append(node111.neighbors, node111a);
	node111.neighbors = append(node111.neighbors, node111b);
	node111.neighbors = append(node111.neighbors, node112);
	node112.neighbors = append(node112.neighbors, node112a);
	node112.neighbors = append(node112.neighbors, node112b);
	node112.neighbors = append(node112.neighbors, node113);
	node113.neighbors = append(node113.neighbors, node113a);
	node113.neighbors = append(node113.neighbors, node113b);
	node113.neighbors = append(node113.neighbors, node114);
	node114.neighbors = append(node114.neighbors, node114a);
	node114.neighbors = append(node114.neighbors, node114b);
	node114.neighbors = append(node114.neighbors, node115);
	node115.neighbors = append(node115.neighbors, node115a);
	node115.neighbors = append(node115.neighbors, node115b);
	node115.neighbors = append(node115.neighbors, node116);
	node116.neighbors = append(node116.neighbors, node116a);
	node116.neighbors = append(node116.neighbors, node116b);
	node116.neighbors = append(node116.neighbors, node117);
	node117.neighbors = append(node117.neighbors, node117a);
	node117.neighbors = append(node117.neighbors, node117b);
	node117.neighbors = append(node117.neighbors, node118);
	node118.neighbors = append(node118.neighbors, node118a);
	node118.neighbors = append(node118.neighbors, node118b);
	node118.neighbors = append(node118.neighbors, node119);
	node119.neighbors = append(node119.neighbors, node119a);
	node119.neighbors = append(node119.neighbors, node119b);
	node119.neighbors = append(node119.neighbors, node120);
	node120.neighbors = append(node120.neighbors, node120a);
	node120.neighbors = append(node120.neighbors, node120b);
	node120.neighbors = append(node120.neighbors, node121);
	node121.neighbors = append(node121.neighbors, node121a);
	node121.neighbors = append(node121.neighbors, node121b);
	node121.neighbors = append(node121.neighbors, node122);
	node122.neighbors = append(node122.neighbors, node122a);
	node122.neighbors = append(node122.neighbors, node122b);
	node122.neighbors = append(node122.neighbors, node123);
	node123.neighbors = append(node123.neighbors, node123a);
	node123.neighbors = append(node123.neighbors, node123b);
	node123.neighbors = append(node123.neighbors, node124);
	node124.neighbors = append(node124.neighbors, node124a);
	node124.neighbors = append(node124.neighbors, node124b);
	node124.neighbors = append(node124.neighbors, node125);
	node125.neighbors = append(node125.neighbors, node125a);
	node125.neighbors = append(node125.neighbors, node125b);
	node125.neighbors = append(node125.neighbors, node126);
	node126.neighbors = append(node126.neighbors, node126a);
	node126.neighbors = append(node126.neighbors, node126b);
	node126.neighbors = append(node126.neighbors, node127);
	node127.neighbors = append(node127.neighbors, node127a);
	node127.neighbors = append(node127.neighbors, node127b);
	node127.neighbors = append(node127.neighbors, node128);
	node128.neighbors = append(node128.neighbors, node128a);
	node128.neighbors = append(node128.neighbors, node128b);
	node128.neighbors = append(node128.neighbors, node129);
	node129.neighbors = append(node129.neighbors, node129a);
	node129.neighbors = append(node129.neighbors, node129b);
	node129.neighbors = append(node129.neighbors, node130);
	node130.neighbors = append(node130.neighbors, node130a);
	node130.neighbors = append(node130.neighbors, node130b);
	node130.neighbors = append(node130.neighbors, node131);
	node131.neighbors = append(node131.neighbors, node131a);
	node131.neighbors = append(node131.neighbors, node131b);
	node131.neighbors = append(node131.neighbors, node132);
	node132.neighbors = append(node132.neighbors, node132a);
	node132.neighbors = append(node132.neighbors, node132b);
	node132.neighbors = append(node132.neighbors, node133);
	node133.neighbors = append(node133.neighbors, node133a);
	node133.neighbors = append(node133.neighbors, node133b);
	node133.neighbors = append(node133.neighbors, node134);
	node134.neighbors = append(node134.neighbors, node134a);
	node134.neighbors = append(node134.neighbors, node134b);
	node134.neighbors = append(node134.neighbors, node135);
	node135.neighbors = append(node135.neighbors, node135a);
	node135.neighbors = append(node135.neighbors, node135b);
	node135.neighbors = append(node135.neighbors, node136);
	node136.neighbors = append(node136.neighbors, node136a);
	node136.neighbors = append(node136.neighbors, node136b);
	node136.neighbors = append(node136.neighbors, node137);
	node137.neighbors = append(node137.neighbors, node137a);
	node137.neighbors = append(node137.neighbors, node137b);
	node137.neighbors = append(node137.neighbors, node138);
	node138.neighbors = append(node138.neighbors, node138a);
	node138.neighbors = append(node138.neighbors, node138b);
	node138.neighbors = append(node138.neighbors, node139);
	node139.neighbors = append(node139.neighbors, node139a);
	node139.neighbors = append(node139.neighbors, node139b);
	node139.neighbors = append(node139.neighbors, node140);
	node140.neighbors = append(node140.neighbors, node140a);
	node140.neighbors = append(node140.neighbors, node140b);
	node140.neighbors = append(node140.neighbors, node141);
	node141.neighbors = append(node141.neighbors, node141a);
	node141.neighbors = append(node141.neighbors, node141b);
	node141.neighbors = append(node141.neighbors, node142);
	node142.neighbors = append(node142.neighbors, node142a);
	node142.neighbors = append(node142.neighbors, node142b);
	node142.neighbors = append(node142.neighbors, node143);
	node143.neighbors = append(node143.neighbors, node143a);
	node143.neighbors = append(node143.neighbors, node143b);
	node143.neighbors = append(node143.neighbors, node144);
	node144.neighbors = append(node144.neighbors, node144a);
	node144.neighbors = append(node144.neighbors, node144b);
	node144.neighbors = append(node144.neighbors, node145);
	node145.neighbors = append(node145.neighbors, node145a);
	node145.neighbors = append(node145.neighbors, node145b);
	node145.neighbors = append(node145.neighbors, node146);
	node146.neighbors = append(node146.neighbors, node146a);
	node146.neighbors = append(node146.neighbors, node146b);
	node146.neighbors = append(node146.neighbors, node147);
	node147.neighbors = append(node147.neighbors, node147a);
	node147.neighbors = append(node147.neighbors, node147b);
	node147.neighbors = append(node147.neighbors, node148);
	node148.neighbors = append(node148.neighbors, node148a);
	node148.neighbors = append(node148.neighbors, node148b);
	node148.neighbors = append(node148.neighbors, node149);
	node149.neighbors = append(node149.neighbors, node149a);
	node149.neighbors = append(node149.neighbors, node149b);
	node149.neighbors = append(node149.neighbors, node150);
	node150.neighbors = append(node150.neighbors, node150a);
	node150.neighbors = append(node150.neighbors, node150b);
	node150.neighbors = append(node150.neighbors, node151);
	node151.neighbors = append(node151.neighbors, node151a);
	node151.neighbors = append(node151.neighbors, node151b);
	node151.neighbors = append(node151.neighbors, node152);
	node152.neighbors = append(node152.neighbors, node152a);
	node152.neighbors = append(node152.neighbors, node152b);
	node152.neighbors = append(node152.neighbors, node153);
	node153.neighbors = append(node153.neighbors, node153a);
	node153.neighbors = append(node153.neighbors, node153b);
	node153.neighbors = append(node153.neighbors, node154);
	node154.neighbors = append(node154.neighbors, node154a);
	node154.neighbors = append(node154.neighbors, node154b);
	node154.neighbors = append(node154.neighbors, node155);
	node155.neighbors = append(node155.neighbors, node155a);
	node155.neighbors = append(node155.neighbors, node155b);
	node155.neighbors = append(node155.neighbors, node156);
	node156.neighbors = append(node156.neighbors, node156a);
	node156.neighbors = append(node156.neighbors, node156b);
	node156.neighbors = append(node156.neighbors, node157);
	node157.neighbors = append(node157.neighbors, node157a);
	node157.neighbors = append(node157.neighbors, node157b);
	node157.neighbors = append(node157.neighbors, node158);
	node158.neighbors = append(node158.neighbors, node158a);
	node158.neighbors = append(node158.neighbors, node158b);
	node158.neighbors = append(node158.neighbors, node159);
	node159.neighbors = append(node159.neighbors, node159a);
	node159.neighbors = append(node159.neighbors, node159b);
	node159.neighbors = append(node159.neighbors, node160);
	node160.neighbors = append(node160.neighbors, node160a);
	node160.neighbors = append(node160.neighbors, node160b);
	node160.neighbors = append(node160.neighbors, node161);
	node161.neighbors = append(node161.neighbors, node161a);
	node161.neighbors = append(node161.neighbors, node161b);
	node161.neighbors = append(node161.neighbors, node162);
	node162.neighbors = append(node162.neighbors, node162a);
	node162.neighbors = append(node162.neighbors, node162b);
	node162.neighbors = append(node162.neighbors, node163);
	node163.neighbors = append(node163.neighbors, node163a);
	node163.neighbors = append(node163.neighbors, node163b);
	node163.neighbors = append(node163.neighbors, node164);
	node164.neighbors = append(node164.neighbors, node164a);
	node164.neighbors = append(node164.neighbors, node164b);
	node164.neighbors = append(node164.neighbors, node165);
	node165.neighbors = append(node165.neighbors, node165a);
	node165.neighbors = append(node165.neighbors, node165b);
	node165.neighbors = append(node165.neighbors, node166);
	node166.neighbors = append(node166.neighbors, node166a);
	node166.neighbors = append(node166.neighbors, node166b);
	node166.neighbors = append(node166.neighbors, node167);
	node167.neighbors = append(node167.neighbors, node167a);
	node167.neighbors = append(node167.neighbors, node167b);
	node167.neighbors = append(node167.neighbors, node168);
	node168.neighbors = append(node168.neighbors, node168a);
	node168.neighbors = append(node168.neighbors, node168b);
	node168.neighbors = append(node168.neighbors, node169);
	node169.neighbors = append(node169.neighbors, node169a);
	node169.neighbors = append(node169.neighbors, node169b);
	node169.neighbors = append(node169.neighbors, node170);
	node170.neighbors = append(node170.neighbors, node170a);
	node170.neighbors = append(node170.neighbors, node170b);
	node170.neighbors = append(node170.neighbors, node171);
	node171.neighbors = append(node171.neighbors, node171a);
	node171.neighbors = append(node171.neighbors, node171b);
	node171.neighbors = append(node171.neighbors, node172);
	node172.neighbors = append(node172.neighbors, node172a);
	node172.neighbors = append(node172.neighbors, node172b);
	node172.neighbors = append(node172.neighbors, node173);
	node173.neighbors = append(node173.neighbors, node173a);
	node173.neighbors = append(node173.neighbors, node173b);
	node173.neighbors = append(node173.neighbors, node174);
	node174.neighbors = append(node174.neighbors, node174a);
	node174.neighbors = append(node174.neighbors, node174b);
	node174.neighbors = append(node174.neighbors, node175);
	node175.neighbors = append(node175.neighbors, node175a);
	node175.neighbors = append(node175.neighbors, node175b);
	node175.neighbors = append(node175.neighbors, node176);
	node176.neighbors = append(node176.neighbors, node176a);
	node176.neighbors = append(node176.neighbors, node176b);
	node176.neighbors = append(node176.neighbors, node177);
	node177.neighbors = append(node177.neighbors, node177a);
	node177.neighbors = append(node177.neighbors, node177b);
	node177.neighbors = append(node177.neighbors, node178);
	node178.neighbors = append(node178.neighbors, node178a);
	node178.neighbors = append(node178.neighbors, node178b);
	node178.neighbors = append(node178.neighbors, node179);
	node179.neighbors = append(node179.neighbors, node179a);
	node179.neighbors = append(node179.neighbors, node179b);
	node179.neighbors = append(node179.neighbors, node180);
	node180.neighbors = append(node180.neighbors, node180a);
	node180.neighbors = append(node180.neighbors, node180b);
	node180.neighbors = append(node180.neighbors, node181);
	node181.neighbors = append(node181.neighbors, node181a);
	node181.neighbors = append(node181.neighbors, node181b);
	node181.neighbors = append(node181.neighbors, node182);
	node182.neighbors = append(node182.neighbors, node182a);
	node182.neighbors = append(node182.neighbors, node182b);
	node182.neighbors = append(node182.neighbors, node183);
	node183.neighbors = append(node183.neighbors, node183a);
	node183.neighbors = append(node183.neighbors, node183b);
	node183.neighbors = append(node183.neighbors, node184);
	node184.neighbors = append(node184.neighbors, node184a);
	node184.neighbors = append(node184.neighbors, node184b);
	node184.neighbors = append(node184.neighbors, node185);
	node185.neighbors = append(node185.neighbors, node185a);
	node185.neighbors = append(node185.neighbors, node185b);
	node185.neighbors = append(node185.neighbors, node186);
	node186.neighbors = append(node186.neighbors, node186a);
	node186.neighbors = append(node186.neighbors, node186b);
	node186.neighbors = append(node186.neighbors, node187);
	node187.neighbors = append(node187.neighbors, node187a);
	node187.neighbors = append(node187.neighbors, node187b);
	node187.neighbors = append(node187.neighbors, node188);
	node188.neighbors = append(node188.neighbors, node188a);
	node188.neighbors = append(node188.neighbors, node188b);
	node188.neighbors = append(node188.neighbors, node189);
	node189.neighbors = append(node189.neighbors, node189a);
	node189.neighbors = append(node189.neighbors, node189b);
	node189.neighbors = append(node189.neighbors, node190);
	node190.neighbors = append(node190.neighbors, node190a);
	node190.neighbors = append(node190.neighbors, node190b);
	node190.neighbors = append(node190.neighbors, node191);
	node191.neighbors = append(node191.neighbors, node191a);
	node191.neighbors = append(node191.neighbors, node191b);
	node191.neighbors = append(node191.neighbors, node192);
	node192.neighbors = append(node192.neighbors, node192a);
	node192.neighbors = append(node192.neighbors, node192b);
	node192.neighbors = append(node192.neighbors, node193);
	node193.neighbors = append(node193.neighbors, node193a);
	node193.neighbors = append(node193.neighbors, node193b);
	node193.neighbors = append(node193.neighbors, node194);
	node194.neighbors = append(node194.neighbors, node194a);
	node194.neighbors = append(node194.neighbors, node194b);
	node194.neighbors = append(node194.neighbors, node195);
	node195.neighbors = append(node195.neighbors, node195a);
	node195.neighbors = append(node195.neighbors, node195b);
	node195.neighbors = append(node195.neighbors, node196);
	node196.neighbors = append(node196.neighbors, node196a);
	node196.neighbors = append(node196.neighbors, node196b);
	node196.neighbors = append(node196.neighbors, node197);
	node197.neighbors = append(node197.neighbors, node197a);
	node197.neighbors = append(node197.neighbors, node197b);
	node197.neighbors = append(node197.neighbors, node198);
	node198.neighbors = append(node198.neighbors, node198a);
	node198.neighbors = append(node198.neighbors, node198b);
	node198.neighbors = append(node198.neighbors, node199);
	node199.neighbors = append(node199.neighbors, node199a
	node199.neighbors = append(node199.neighbors, node199b
	node199a.neighbors = append(node199a.neighbors, node199
	node199a.neighbors = append(node199a.neighbors, node199b
	node199b.neighbors = append(node199b.neighbors, node199
	node199b.neighbors = append(node199b.neighbors, node199a
	triangleGraph.nodes = append(triangleGraph.nodes, node0);
	triangleGraph.nodes = append(triangleGraph.nodes, node0a);
	triangleGraph.nodes = append(triangleGraph.nodes, node0b);
	triangleGraph.nodes = append(triangleGraph.nodes, node1);
	triangleGraph.nodes = append(triangleGraph.nodes, node1a);
	triangleGraph.nodes = append(triangleGraph.nodes, node1b);
	triangleGraph.nodes = append(triangleGraph.nodes, node2);
	triangleGraph.nodes = append(triangleGraph.nodes, node2a);
	triangleGraph.nodes = append(triangleGraph.nodes, node2b);
	triangleGraph.nodes = append(triangleGraph.nodes, node3);
	triangleGraph.nodes = append(triangleGraph.nodes, node3a);
	triangleGraph.nodes = append(triangleGraph.nodes, node3b);
	triangleGraph.nodes = append(triangleGraph.nodes, node4);
	triangleGraph.nodes = append(triangleGraph.nodes, node4a);
	triangleGraph.nodes = append(triangleGraph.nodes, node4b);
	triangleGraph.nodes = append(triangleGraph.nodes, node5);
	triangleGraph.nodes = append(triangleGraph.nodes, node5a);
	triangleGraph.nodes = append(triangleGraph.nodes, node5b);
	triangleGraph.nodes = append(triangleGraph.nodes, node6);
	triangleGraph.nodes = append(triangleGraph.nodes, node6a);
	triangleGraph.nodes = append(triangleGraph.nodes, node6b);
	triangleGraph.nodes = append(triangleGraph.nodes, node7);
	triangleGraph.nodes = append(triangleGraph.nodes, node7a);
	triangleGraph.nodes = append(triangleGraph.nodes, node7b);
	triangleGraph.nodes = append(triangleGraph.nodes, node8);
	triangleGraph.nodes = append(triangleGraph.nodes, node8a);
	triangleGraph.nodes = append(triangleGraph.nodes, node8b);
	triangleGraph.nodes = append(triangleGraph.nodes, node9);
	triangleGraph.nodes = append(triangleGraph.nodes, node9a);
	triangleGraph.nodes = append(triangleGraph.nodes, node9b);
	triangleGraph.nodes = append(triangleGraph.nodes, node10);
	triangleGraph.nodes = append(triangleGraph.nodes, node10a);
	triangleGraph.nodes = append(triangleGraph.nodes, node10b);
	triangleGraph.nodes = append(triangleGraph.nodes, node11);
	triangleGraph.nodes = append(triangleGraph.nodes, node11a);
	triangleGraph.nodes = append(triangleGraph.nodes, node11b);
	triangleGraph.nodes = append(triangleGraph.nodes, node12);
	triangleGraph.nodes = append(triangleGraph.nodes, node12a);
	triangleGraph.nodes = append(triangleGraph.nodes, node12b);
	triangleGraph.nodes = append(triangleGraph.nodes, node13);
	triangleGraph.nodes = append(triangleGraph.nodes, node13a);
	triangleGraph.nodes = append(triangleGraph.nodes, node13b);
	triangleGraph.nodes = append(triangleGraph.nodes, node14);
	triangleGraph.nodes = append(triangleGraph.nodes, node14a);
	triangleGraph.nodes = append(triangleGraph.nodes, node14b);
	triangleGraph.nodes = append(triangleGraph.nodes, node15);
	triangleGraph.nodes = append(triangleGraph.nodes, node15a);
	triangleGraph.nodes = append(triangleGraph.nodes, node15b);
	triangleGraph.nodes = append(triangleGraph.nodes, node16);
	triangleGraph.nodes = append(triangleGraph.nodes, node16a);
	triangleGraph.nodes = append(triangleGraph.nodes, node16b);
	triangleGraph.nodes = append(triangleGraph.nodes, node17);
	triangleGraph.nodes = append(triangleGraph.nodes, node17a);
	triangleGraph.nodes = append(triangleGraph.nodes, node17b);
	triangleGraph.nodes = append(triangleGraph.nodes, node18);
	triangleGraph.nodes = append(triangleGraph.nodes, node18a);
	triangleGraph.nodes = append(triangleGraph.nodes, node18b);
	triangleGraph.nodes = append(triangleGraph.nodes, node19);
	triangleGraph.nodes = append(triangleGraph.nodes, node19a);
	triangleGraph.nodes = append(triangleGraph.nodes, node19b);
	triangleGraph.nodes = append(triangleGraph.nodes, node20);
	triangleGraph.nodes = append(triangleGraph.nodes, node20a);
	triangleGraph.nodes = append(triangleGraph.nodes, node20b);
	triangleGraph.nodes = append(triangleGraph.nodes, node21);
	triangleGraph.nodes = append(triangleGraph.nodes, node21a);
	triangleGraph.nodes = append(triangleGraph.nodes, node21b);
	triangleGraph.nodes = append(triangleGraph.nodes, node22);
	triangleGraph.nodes = append(triangleGraph.nodes, node22a);
	triangleGraph.nodes = append(triangleGraph.nodes, node22b);
	triangleGraph.nodes = append(triangleGraph.nodes, node23);
	triangleGraph.nodes = append(triangleGraph.nodes, node23a);
	triangleGraph.nodes = append(triangleGraph.nodes, node23b);
	triangleGraph.nodes = append(triangleGraph.nodes, node24);
	triangleGraph.nodes = append(triangleGraph.nodes, node24a);
	triangleGraph.nodes = append(triangleGraph.nodes, node24b);
	triangleGraph.nodes = append(triangleGraph.nodes, node25);
	triangleGraph.nodes = append(triangleGraph.nodes, node25a);
	triangleGraph.nodes = append(triangleGraph.nodes, node25b);
	triangleGraph.nodes = append(triangleGraph.nodes, node26);
	triangleGraph.nodes = append(triangleGraph.nodes, node26a);
	triangleGraph.nodes = append(triangleGraph.nodes, node26b);
	triangleGraph.nodes = append(triangleGraph.nodes, node27);
	triangleGraph.nodes = append(triangleGraph.nodes, node27a);
	triangleGraph.nodes = append(triangleGraph.nodes, node27b);
	triangleGraph.nodes = append(triangleGraph.nodes, node28);
	triangleGraph.nodes = append(triangleGraph.nodes, node28a);
	triangleGraph.nodes = append(triangleGraph.nodes, node28b);
	triangleGraph.nodes = append(triangleGraph.nodes, node29);
	triangleGraph.nodes = append(triangleGraph.nodes, node29a);
	triangleGraph.nodes = append(triangleGraph.nodes, node29b);
	triangleGraph.nodes = append(triangleGraph.nodes, node30);
	triangleGraph.nodes = append(triangleGraph.nodes, node30a);
	triangleGraph.nodes = append(triangleGraph.nodes, node30b);
	triangleGraph.nodes = append(triangleGraph.nodes, node31);
	triangleGraph.nodes = append(triangleGraph.nodes, node31a);
	triangleGraph.nodes = append(triangleGraph.nodes, node31b);
	triangleGraph.nodes = append(triangleGraph.nodes, node32);
	triangleGraph.nodes = append(triangleGraph.nodes, node32a);
	triangleGraph.nodes = append(triangleGraph.nodes, node32b);
	triangleGraph.nodes = append(triangleGraph.nodes, node33);
	triangleGraph.nodes = append(triangleGraph.nodes, node33a);
	triangleGraph.nodes = append(triangleGraph.nodes, node33b);
	triangleGraph.nodes = append(triangleGraph.nodes, node34);
	triangleGraph.nodes = append(triangleGraph.nodes, node34a);
	triangleGraph.nodes = append(triangleGraph.nodes, node34b);
	triangleGraph.nodes = append(triangleGraph.nodes, node35);
	triangleGraph.nodes = append(triangleGraph.nodes, node35a);
	triangleGraph.nodes = append(triangleGraph.nodes, node35b);
	triangleGraph.nodes = append(triangleGraph.nodes, node36);
	triangleGraph.nodes = append(triangleGraph.nodes, node36a);
	triangleGraph.nodes = append(triangleGraph.nodes, node36b);
	triangleGraph.nodes = append(triangleGraph.nodes, node37);
	triangleGraph.nodes = append(triangleGraph.nodes, node37a);
	triangleGraph.nodes = append(triangleGraph.nodes, node37b);
	triangleGraph.nodes = append(triangleGraph.nodes, node38);
	triangleGraph.nodes = append(triangleGraph.nodes, node38a);
	triangleGraph.nodes = append(triangleGraph.nodes, node38b);
	triangleGraph.nodes = append(triangleGraph.nodes, node39);
	triangleGraph.nodes = append(triangleGraph.nodes, node39a);
	triangleGraph.nodes = append(triangleGraph.nodes, node39b);
	triangleGraph.nodes = append(triangleGraph.nodes, node40);
	triangleGraph.nodes = append(triangleGraph.nodes, node40a);
	triangleGraph.nodes = append(triangleGraph.nodes, node40b);
	triangleGraph.nodes = append(triangleGraph.nodes, node41);
	triangleGraph.nodes = append(triangleGraph.nodes, node41a);
	triangleGraph.nodes = append(triangleGraph.nodes, node41b);
	triangleGraph.nodes = append(triangleGraph.nodes, node42);
	triangleGraph.nodes = append(triangleGraph.nodes, node42a);
	triangleGraph.nodes = append(triangleGraph.nodes, node42b);
	triangleGraph.nodes = append(triangleGraph.nodes, node43);
	triangleGraph.nodes = append(triangleGraph.nodes, node43a);
	triangleGraph.nodes = append(triangleGraph.nodes, node43b);
	triangleGraph.nodes = append(triangleGraph.nodes, node44);
	triangleGraph.nodes = append(triangleGraph.nodes, node44a);
	triangleGraph.nodes = append(triangleGraph.nodes, node44b);
	triangleGraph.nodes = append(triangleGraph.nodes, node45);
	triangleGraph.nodes = append(triangleGraph.nodes, node45a);
	triangleGraph.nodes = append(triangleGraph.nodes, node45b);
	triangleGraph.nodes = append(triangleGraph.nodes, node46);
	triangleGraph.nodes = append(triangleGraph.nodes, node46a);
	triangleGraph.nodes = append(triangleGraph.nodes, node46b);
	triangleGraph.nodes = append(triangleGraph.nodes, node47);
	triangleGraph.nodes = append(triangleGraph.nodes, node47a);
	triangleGraph.nodes = append(triangleGraph.nodes, node47b);
	triangleGraph.nodes = append(triangleGraph.nodes, node48);
	triangleGraph.nodes = append(triangleGraph.nodes, node48a);
	triangleGraph.nodes = append(triangleGraph.nodes, node48b);
	triangleGraph.nodes = append(triangleGraph.nodes, node49);
	triangleGraph.nodes = append(triangleGraph.nodes, node49a);
	triangleGraph.nodes = append(triangleGraph.nodes, node49b);
	triangleGraph.nodes = append(triangleGraph.nodes, node50);
	triangleGraph.nodes = append(triangleGraph.nodes, node50a);
	triangleGraph.nodes = append(triangleGraph.nodes, node50b);
	triangleGraph.nodes = append(triangleGraph.nodes, node51);
	triangleGraph.nodes = append(triangleGraph.nodes, node51a);
	triangleGraph.nodes = append(triangleGraph.nodes, node51b);
	triangleGraph.nodes = append(triangleGraph.nodes, node52);
	triangleGraph.nodes = append(triangleGraph.nodes, node52a);
	triangleGraph.nodes = append(triangleGraph.nodes, node52b);
	triangleGraph.nodes = append(triangleGraph.nodes, node53);
	triangleGraph.nodes = append(triangleGraph.nodes, node53a);
	triangleGraph.nodes = append(triangleGraph.nodes, node53b);
	triangleGraph.nodes = append(triangleGraph.nodes, node54);
	triangleGraph.nodes = append(triangleGraph.nodes, node54a);
	triangleGraph.nodes = append(triangleGraph.nodes, node54b);
	triangleGraph.nodes = append(triangleGraph.nodes, node55);
	triangleGraph.nodes = append(triangleGraph.nodes, node55a);
	triangleGraph.nodes = append(triangleGraph.nodes, node55b);
	triangleGraph.nodes = append(triangleGraph.nodes, node56);
	triangleGraph.nodes = append(triangleGraph.nodes, node56a);
	triangleGraph.nodes = append(triangleGraph.nodes, node56b);
	triangleGraph.nodes = append(triangleGraph.nodes, node57);
	triangleGraph.nodes = append(triangleGraph.nodes, node57a);
	triangleGraph.nodes = append(triangleGraph.nodes, node57b);
	triangleGraph.nodes = append(triangleGraph.nodes, node58);
	triangleGraph.nodes = append(triangleGraph.nodes, node58a);
	triangleGraph.nodes = append(triangleGraph.nodes, node58b);
	triangleGraph.nodes = append(triangleGraph.nodes, node59);
	triangleGraph.nodes = append(triangleGraph.nodes, node59a);
	triangleGraph.nodes = append(triangleGraph.nodes, node59b);
	triangleGraph.nodes = append(triangleGraph.nodes, node60);
	triangleGraph.nodes = append(triangleGraph.nodes, node60a);
	triangleGraph.nodes = append(triangleGraph.nodes, node60b);
	triangleGraph.nodes = append(triangleGraph.nodes, node61);
	triangleGraph.nodes = append(triangleGraph.nodes, node61a);
	triangleGraph.nodes = append(triangleGraph.nodes, node61b);
	triangleGraph.nodes = append(triangleGraph.nodes, node62);
	triangleGraph.nodes = append(triangleGraph.nodes, node62a);
	triangleGraph.nodes = append(triangleGraph.nodes, node62b);
	triangleGraph.nodes = append(triangleGraph.nodes, node63);
	triangleGraph.nodes = append(triangleGraph.nodes, node63a);
	triangleGraph.nodes = append(triangleGraph.nodes, node63b);
	triangleGraph.nodes = append(triangleGraph.nodes, node64);
	triangleGraph.nodes = append(triangleGraph.nodes, node64a);
	triangleGraph.nodes = append(triangleGraph.nodes, node64b);
	triangleGraph.nodes = append(triangleGraph.nodes, node65);
	triangleGraph.nodes = append(triangleGraph.nodes, node65a);
	triangleGraph.nodes = append(triangleGraph.nodes, node65b);
	triangleGraph.nodes = append(triangleGraph.nodes, node66);
	triangleGraph.nodes = append(triangleGraph.nodes, node66a);
	triangleGraph.nodes = append(triangleGraph.nodes, node66b);
	triangleGraph.nodes = append(triangleGraph.nodes, node67);
	triangleGraph.nodes = append(triangleGraph.nodes, node67a);
	triangleGraph.nodes = append(triangleGraph.nodes, node67b);
	triangleGraph.nodes = append(triangleGraph.nodes, node68);
	triangleGraph.nodes = append(triangleGraph.nodes, node68a);
	triangleGraph.nodes = append(triangleGraph.nodes, node68b);
	triangleGraph.nodes = append(triangleGraph.nodes, node69);
	triangleGraph.nodes = append(triangleGraph.nodes, node69a);
	triangleGraph.nodes = append(triangleGraph.nodes, node69b);
	triangleGraph.nodes = append(triangleGraph.nodes, node70);
	triangleGraph.nodes = append(triangleGraph.nodes, node70a);
	triangleGraph.nodes = append(triangleGraph.nodes, node70b);
	triangleGraph.nodes = append(triangleGraph.nodes, node71);
	triangleGraph.nodes = append(triangleGraph.nodes, node71a);
	triangleGraph.nodes = append(triangleGraph.nodes, node71b);
	triangleGraph.nodes = append(triangleGraph.nodes, node72);
	triangleGraph.nodes = append(triangleGraph.nodes, node72a);
	triangleGraph.nodes = append(triangleGraph.nodes, node72b);
	triangleGraph.nodes = append(triangleGraph.nodes, node73);
	triangleGraph.nodes = append(triangleGraph.nodes, node73a);
	triangleGraph.nodes = append(triangleGraph.nodes, node73b);
	triangleGraph.nodes = append(triangleGraph.nodes, node74);
	triangleGraph.nodes = append(triangleGraph.nodes, node74a);
	triangleGraph.nodes = append(triangleGraph.nodes, node74b);
	triangleGraph.nodes = append(triangleGraph.nodes, node75);
	triangleGraph.nodes = append(triangleGraph.nodes, node75a);
	triangleGraph.nodes = append(triangleGraph.nodes, node75b);
	triangleGraph.nodes = append(triangleGraph.nodes, node76);
	triangleGraph.nodes = append(triangleGraph.nodes, node76a);
	triangleGraph.nodes = append(triangleGraph.nodes, node76b);
	triangleGraph.nodes = append(triangleGraph.nodes, node77);
	triangleGraph.nodes = append(triangleGraph.nodes, node77a);
	triangleGraph.nodes = append(triangleGraph.nodes, node77b);
	triangleGraph.nodes = append(triangleGraph.nodes, node78);
	triangleGraph.nodes = append(triangleGraph.nodes, node78a);
	triangleGraph.nodes = append(triangleGraph.nodes, node78b);
	triangleGraph.nodes = append(triangleGraph.nodes, node79);
	triangleGraph.nodes = append(triangleGraph.nodes, node79a);
	triangleGraph.nodes = append(triangleGraph.nodes, node79b);
	triangleGraph.nodes = append(triangleGraph.nodes, node80);
	triangleGraph.nodes = append(triangleGraph.nodes, node80a);
	triangleGraph.nodes = append(triangleGraph.nodes, node80b);
	triangleGraph.nodes = append(triangleGraph.nodes, node81);
	triangleGraph.nodes = append(triangleGraph.nodes, node81a);
	triangleGraph.nodes = append(triangleGraph.nodes, node81b);
	triangleGraph.nodes = append(triangleGraph.nodes, node82);
	triangleGraph.nodes = append(triangleGraph.nodes, node82a);
	triangleGraph.nodes = append(triangleGraph.nodes, node82b);
	triangleGraph.nodes = append(triangleGraph.nodes, node83);
	triangleGraph.nodes = append(triangleGraph.nodes, node83a);
	triangleGraph.nodes = append(triangleGraph.nodes, node83b);
	triangleGraph.nodes = append(triangleGraph.nodes, node84);
	triangleGraph.nodes = append(triangleGraph.nodes, node84a);
	triangleGraph.nodes = append(triangleGraph.nodes, node84b);
	triangleGraph.nodes = append(triangleGraph.nodes, node85);
	triangleGraph.nodes = append(triangleGraph.nodes, node85a);
	triangleGraph.nodes = append(triangleGraph.nodes, node85b);
	triangleGraph.nodes = append(triangleGraph.nodes, node86);
	triangleGraph.nodes = append(triangleGraph.nodes, node86a);
	triangleGraph.nodes = append(triangleGraph.nodes, node86b);
	triangleGraph.nodes = append(triangleGraph.nodes, node87);
	triangleGraph.nodes = append(triangleGraph.nodes, node87a);
	triangleGraph.nodes = append(triangleGraph.nodes, node87b);
	triangleGraph.nodes = append(triangleGraph.nodes, node88);
	triangleGraph.nodes = append(triangleGraph.nodes, node88a);
	triangleGraph.nodes = append(triangleGraph.nodes, node88b);
	triangleGraph.nodes = append(triangleGraph.nodes, node89);
	triangleGraph.nodes = append(triangleGraph.nodes, node89a);
	triangleGraph.nodes = append(triangleGraph.nodes, node89b);
	triangleGraph.nodes = append(triangleGraph.nodes, node90);
	triangleGraph.nodes = append(triangleGraph.nodes, node90a);
	triangleGraph.nodes = append(triangleGraph.nodes, node90b);
	triangleGraph.nodes = append(triangleGraph.nodes, node91);
	triangleGraph.nodes = append(triangleGraph.nodes, node91a);
	triangleGraph.nodes = append(triangleGraph.nodes, node91b);
	triangleGraph.nodes = append(triangleGraph.nodes, node92);
	triangleGraph.nodes = append(triangleGraph.nodes, node92a);
	triangleGraph.nodes = append(triangleGraph.nodes, node92b);
	triangleGraph.nodes = append(triangleGraph.nodes, node93);
	triangleGraph.nodes = append(triangleGraph.nodes, node93a);
	triangleGraph.nodes = append(triangleGraph.nodes, node93b);
	triangleGraph.nodes = append(triangleGraph.nodes, node94);
	triangleGraph.nodes = append(triangleGraph.nodes, node94a);
	triangleGraph.nodes = append(triangleGraph.nodes, node94b);
	triangleGraph.nodes = append(triangleGraph.nodes, node95);
	triangleGraph.nodes = append(triangleGraph.nodes, node95a);
	triangleGraph.nodes = append(triangleGraph.nodes, node95b);
	triangleGraph.nodes = append(triangleGraph.nodes, node96);
	triangleGraph.nodes = append(triangleGraph.nodes, node96a);
	triangleGraph.nodes = append(triangleGraph.nodes, node96b);
	triangleGraph.nodes = append(triangleGraph.nodes, node97);
	triangleGraph.nodes = append(triangleGraph.nodes, node97a);
	triangleGraph.nodes = append(triangleGraph.nodes, node97b);
	triangleGraph.nodes = append(triangleGraph.nodes, node98);
	triangleGraph.nodes = append(triangleGraph.nodes, node98a);
	triangleGraph.nodes = append(triangleGraph.nodes, node98b);
	triangleGraph.nodes = append(triangleGraph.nodes, node99);
	triangleGraph.nodes = append(triangleGraph.nodes, node99a);
	triangleGraph.nodes = append(triangleGraph.nodes, node99b);
	triangleGraph.nodes = append(triangleGraph.nodes, node100);
	triangleGraph.nodes = append(triangleGraph.nodes, node100a);
	triangleGraph.nodes = append(triangleGraph.nodes, node100b);
	triangleGraph.nodes = append(triangleGraph.nodes, node101);
	triangleGraph.nodes = append(triangleGraph.nodes, node101a);
	triangleGraph.nodes = append(triangleGraph.nodes, node101b);
	triangleGraph.nodes = append(triangleGraph.nodes, node102);
	triangleGraph.nodes = append(triangleGraph.nodes, node102a);
	triangleGraph.nodes = append(triangleGraph.nodes, node102b);
	triangleGraph.nodes = append(triangleGraph.nodes, node103);
	triangleGraph.nodes = append(triangleGraph.nodes, node103a);
	triangleGraph.nodes = append(triangleGraph.nodes, node103b);
	triangleGraph.nodes = append(triangleGraph.nodes, node104);
	triangleGraph.nodes = append(triangleGraph.nodes, node104a);
	triangleGraph.nodes = append(triangleGraph.nodes, node104b);
	triangleGraph.nodes = append(triangleGraph.nodes, node105);
	triangleGraph.nodes = append(triangleGraph.nodes, node105a);
	triangleGraph.nodes = append(triangleGraph.nodes, node105b);
	triangleGraph.nodes = append(triangleGraph.nodes, node106);
	triangleGraph.nodes = append(triangleGraph.nodes, node106a);
	triangleGraph.nodes = append(triangleGraph.nodes, node106b);
	triangleGraph.nodes = append(triangleGraph.nodes, node107);
	triangleGraph.nodes = append(triangleGraph.nodes, node107a);
	triangleGraph.nodes = append(triangleGraph.nodes, node107b);
	triangleGraph.nodes = append(triangleGraph.nodes, node108);
	triangleGraph.nodes = append(triangleGraph.nodes, node108a);
	triangleGraph.nodes = append(triangleGraph.nodes, node108b);
	triangleGraph.nodes = append(triangleGraph.nodes, node109);
	triangleGraph.nodes = append(triangleGraph.nodes, node109a);
	triangleGraph.nodes = append(triangleGraph.nodes, node109b);
	triangleGraph.nodes = append(triangleGraph.nodes, node110);
	triangleGraph.nodes = append(triangleGraph.nodes, node110a);
	triangleGraph.nodes = append(triangleGraph.nodes, node110b);
	triangleGraph.nodes = append(triangleGraph.nodes, node111);
	triangleGraph.nodes = append(triangleGraph.nodes, node111a);
	triangleGraph.nodes = append(triangleGraph.nodes, node111b);
	triangleGraph.nodes = append(triangleGraph.nodes, node112);
	triangleGraph.nodes = append(triangleGraph.nodes, node112a);
	triangleGraph.nodes = append(triangleGraph.nodes, node112b);
	triangleGraph.nodes = append(triangleGraph.nodes, node113);
	triangleGraph.nodes = append(triangleGraph.nodes, node113a);
	triangleGraph.nodes = append(triangleGraph.nodes, node113b);
	triangleGraph.nodes = append(triangleGraph.nodes, node114);
	triangleGraph.nodes = append(triangleGraph.nodes, node114a);
	triangleGraph.nodes = append(triangleGraph.nodes, node114b);
	triangleGraph.nodes = append(triangleGraph.nodes, node115);
	triangleGraph.nodes = append(triangleGraph.nodes, node115a);
	triangleGraph.nodes = append(triangleGraph.nodes, node115b);
	triangleGraph.nodes = append(triangleGraph.nodes, node116);
	triangleGraph.nodes = append(triangleGraph.nodes, node116a);
	triangleGraph.nodes = append(triangleGraph.nodes, node116b);
	triangleGraph.nodes = append(triangleGraph.nodes, node117);
	triangleGraph.nodes = append(triangleGraph.nodes, node117a);
	triangleGraph.nodes = append(triangleGraph.nodes, node117b);
	triangleGraph.nodes = append(triangleGraph.nodes, node118);
	triangleGraph.nodes = append(triangleGraph.nodes, node118a);
	triangleGraph.nodes = append(triangleGraph.nodes, node118b);
	triangleGraph.nodes = append(triangleGraph.nodes, node119);
	triangleGraph.nodes = append(triangleGraph.nodes, node119a);
	triangleGraph.nodes = append(triangleGraph.nodes, node119b);
	triangleGraph.nodes = append(triangleGraph.nodes, node120);
	triangleGraph.nodes = append(triangleGraph.nodes, node120a);
	triangleGraph.nodes = append(triangleGraph.nodes, node120b);
	triangleGraph.nodes = append(triangleGraph.nodes, node121);
	triangleGraph.nodes = append(triangleGraph.nodes, node121a);
	triangleGraph.nodes = append(triangleGraph.nodes, node121b);
	triangleGraph.nodes = append(triangleGraph.nodes, node122);
	triangleGraph.nodes = append(triangleGraph.nodes, node122a);
	triangleGraph.nodes = append(triangleGraph.nodes, node122b);
	triangleGraph.nodes = append(triangleGraph.nodes, node123);
	triangleGraph.nodes = append(triangleGraph.nodes, node123a);
	triangleGraph.nodes = append(triangleGraph.nodes, node123b);
	triangleGraph.nodes = append(triangleGraph.nodes, node124);
	triangleGraph.nodes = append(triangleGraph.nodes, node124a);
	triangleGraph.nodes = append(triangleGraph.nodes, node124b);
	triangleGraph.nodes = append(triangleGraph.nodes, node125);
	triangleGraph.nodes = append(triangleGraph.nodes, node125a);
	triangleGraph.nodes = append(triangleGraph.nodes, node125b);
	triangleGraph.nodes = append(triangleGraph.nodes, node126);
	triangleGraph.nodes = append(triangleGraph.nodes, node126a);
	triangleGraph.nodes = append(triangleGraph.nodes, node126b);
	triangleGraph.nodes = append(triangleGraph.nodes, node127);
	triangleGraph.nodes = append(triangleGraph.nodes, node127a);
	triangleGraph.nodes = append(triangleGraph.nodes, node127b);
	triangleGraph.nodes = append(triangleGraph.nodes, node128);
	triangleGraph.nodes = append(triangleGraph.nodes, node128a);
	triangleGraph.nodes = append(triangleGraph.nodes, node128b);
	triangleGraph.nodes = append(triangleGraph.nodes, node129);
	triangleGraph.nodes = append(triangleGraph.nodes, node129a);
	triangleGraph.nodes = append(triangleGraph.nodes, node129b);
	triangleGraph.nodes = append(triangleGraph.nodes, node130);
	triangleGraph.nodes = append(triangleGraph.nodes, node130a);
	triangleGraph.nodes = append(triangleGraph.nodes, node130b);
	triangleGraph.nodes = append(triangleGraph.nodes, node131);
	triangleGraph.nodes = append(triangleGraph.nodes, node131a);
	triangleGraph.nodes = append(triangleGraph.nodes, node131b);
	triangleGraph.nodes = append(triangleGraph.nodes, node132);
	triangleGraph.nodes = append(triangleGraph.nodes, node132a);
	triangleGraph.nodes = append(triangleGraph.nodes, node132b);
	triangleGraph.nodes = append(triangleGraph.nodes, node133);
	triangleGraph.nodes = append(triangleGraph.nodes, node133a);
	triangleGraph.nodes = append(triangleGraph.nodes, node133b);
	triangleGraph.nodes = append(triangleGraph.nodes, node134);
	triangleGraph.nodes = append(triangleGraph.nodes, node134a);
	triangleGraph.nodes = append(triangleGraph.nodes, node134b);
	triangleGraph.nodes = append(triangleGraph.nodes, node135);
	triangleGraph.nodes = append(triangleGraph.nodes, node135a);
	triangleGraph.nodes = append(triangleGraph.nodes, node135b);
	triangleGraph.nodes = append(triangleGraph.nodes, node136);
	triangleGraph.nodes = append(triangleGraph.nodes, node136a);
	triangleGraph.nodes = append(triangleGraph.nodes, node136b);
	triangleGraph.nodes = append(triangleGraph.nodes, node137);
	triangleGraph.nodes = append(triangleGraph.nodes, node137a);
	triangleGraph.nodes = append(triangleGraph.nodes, node137b);
	triangleGraph.nodes = append(triangleGraph.nodes, node138);
	triangleGraph.nodes = append(triangleGraph.nodes, node138a);
	triangleGraph.nodes = append(triangleGraph.nodes, node138b);
	triangleGraph.nodes = append(triangleGraph.nodes, node139);
	triangleGraph.nodes = append(triangleGraph.nodes, node139a);
	triangleGraph.nodes = append(triangleGraph.nodes, node139b);
	triangleGraph.nodes = append(triangleGraph.nodes, node140);
	triangleGraph.nodes = append(triangleGraph.nodes, node140a);
	triangleGraph.nodes = append(triangleGraph.nodes, node140b);
	triangleGraph.nodes = append(triangleGraph.nodes, node141);
	triangleGraph.nodes = append(triangleGraph.nodes, node141a);
	triangleGraph.nodes = append(triangleGraph.nodes, node141b);
	triangleGraph.nodes = append(triangleGraph.nodes, node142);
	triangleGraph.nodes = append(triangleGraph.nodes, node142a);
	triangleGraph.nodes = append(triangleGraph.nodes, node142b);
	triangleGraph.nodes = append(triangleGraph.nodes, node143);
	triangleGraph.nodes = append(triangleGraph.nodes, node143a);
	triangleGraph.nodes = append(triangleGraph.nodes, node143b);
	triangleGraph.nodes = append(triangleGraph.nodes, node144);
	triangleGraph.nodes = append(triangleGraph.nodes, node144a);
	triangleGraph.nodes = append(triangleGraph.nodes, node144b);
	triangleGraph.nodes = append(triangleGraph.nodes, node145);
	triangleGraph.nodes = append(triangleGraph.nodes, node145a);
	triangleGraph.nodes = append(triangleGraph.nodes, node145b);
	triangleGraph.nodes = append(triangleGraph.nodes, node146);
	triangleGraph.nodes = append(triangleGraph.nodes, node146a);
	triangleGraph.nodes = append(triangleGraph.nodes, node146b);
	triangleGraph.nodes = append(triangleGraph.nodes, node147);
	triangleGraph.nodes = append(triangleGraph.nodes, node147a);
	triangleGraph.nodes = append(triangleGraph.nodes, node147b);
	triangleGraph.nodes = append(triangleGraph.nodes, node148);
	triangleGraph.nodes = append(triangleGraph.nodes, node148a);
	triangleGraph.nodes = append(triangleGraph.nodes, node148b);
	triangleGraph.nodes = append(triangleGraph.nodes, node149);
	triangleGraph.nodes = append(triangleGraph.nodes, node149a);
	triangleGraph.nodes = append(triangleGraph.nodes, node149b);
	triangleGraph.nodes = append(triangleGraph.nodes, node150);
	triangleGraph.nodes = append(triangleGraph.nodes, node150a);
	triangleGraph.nodes = append(triangleGraph.nodes, node150b);
	triangleGraph.nodes = append(triangleGraph.nodes, node151);
	triangleGraph.nodes = append(triangleGraph.nodes, node151a);
	triangleGraph.nodes = append(triangleGraph.nodes, node151b);
	triangleGraph.nodes = append(triangleGraph.nodes, node152);
	triangleGraph.nodes = append(triangleGraph.nodes, node152a);
	triangleGraph.nodes = append(triangleGraph.nodes, node152b);
	triangleGraph.nodes = append(triangleGraph.nodes, node153);
	triangleGraph.nodes = append(triangleGraph.nodes, node153a);
	triangleGraph.nodes = append(triangleGraph.nodes, node153b);
	triangleGraph.nodes = append(triangleGraph.nodes, node154);
	triangleGraph.nodes = append(triangleGraph.nodes, node154a);
	triangleGraph.nodes = append(triangleGraph.nodes, node154b);
	triangleGraph.nodes = append(triangleGraph.nodes, node155);
	triangleGraph.nodes = append(triangleGraph.nodes, node155a);
	triangleGraph.nodes = append(triangleGraph.nodes, node155b);
	triangleGraph.nodes = append(triangleGraph.nodes, node156);
	triangleGraph.nodes = append(triangleGraph.nodes, node156a);
	triangleGraph.nodes = append(triangleGraph.nodes, node156b);
	triangleGraph.nodes = append(triangleGraph.nodes, node157);
	triangleGraph.nodes = append(triangleGraph.nodes, node157a);
	triangleGraph.nodes = append(triangleGraph.nodes, node157b);
	triangleGraph.nodes = append(triangleGraph.nodes, node158);
	triangleGraph.nodes = append(triangleGraph.nodes, node158a);
	triangleGraph.nodes = append(triangleGraph.nodes, node158b);
	triangleGraph.nodes = append(triangleGraph.nodes, node159);
	triangleGraph.nodes = append(triangleGraph.nodes, node159a);
	triangleGraph.nodes = append(triangleGraph.nodes, node159b);
	triangleGraph.nodes = append(triangleGraph.nodes, node160);
	triangleGraph.nodes = append(triangleGraph.nodes, node160a);
	triangleGraph.nodes = append(triangleGraph.nodes, node160b);
	triangleGraph.nodes = append(triangleGraph.nodes, node161);
	triangleGraph.nodes = append(triangleGraph.nodes, node161a);
	triangleGraph.nodes = append(triangleGraph.nodes, node161b);
	triangleGraph.nodes = append(triangleGraph.nodes, node162);
	triangleGraph.nodes = append(triangleGraph.nodes, node162a);
	triangleGraph.nodes = append(triangleGraph.nodes, node162b);
	triangleGraph.nodes = append(triangleGraph.nodes, node163);
	triangleGraph.nodes = append(triangleGraph.nodes, node163a);
	triangleGraph.nodes = append(triangleGraph.nodes, node163b);
	triangleGraph.nodes = append(triangleGraph.nodes, node164);
	triangleGraph.nodes = append(triangleGraph.nodes, node164a);
	triangleGraph.nodes = append(triangleGraph.nodes, node164b);
	triangleGraph.nodes = append(triangleGraph.nodes, node165);
	triangleGraph.nodes = append(triangleGraph.nodes, node165a);
	triangleGraph.nodes = append(triangleGraph.nodes, node165b);
	triangleGraph.nodes = append(triangleGraph.nodes, node166);
	triangleGraph.nodes = append(triangleGraph.nodes, node166a);
	triangleGraph.nodes = append(triangleGraph.nodes, node166b);
	triangleGraph.nodes = append(triangleGraph.nodes, node167);
	triangleGraph.nodes = append(triangleGraph.nodes, node167a);
	triangleGraph.nodes = append(triangleGraph.nodes, node167b);
	triangleGraph.nodes = append(triangleGraph.nodes, node168);
	triangleGraph.nodes = append(triangleGraph.nodes, node168a);
	triangleGraph.nodes = append(triangleGraph.nodes, node168b);
	triangleGraph.nodes = append(triangleGraph.nodes, node169);
	triangleGraph.nodes = append(triangleGraph.nodes, node169a);
	triangleGraph.nodes = append(triangleGraph.nodes, node169b);
	triangleGraph.nodes = append(triangleGraph.nodes, node170);
	triangleGraph.nodes = append(triangleGraph.nodes, node170a);
	triangleGraph.nodes = append(triangleGraph.nodes, node170b);
	triangleGraph.nodes = append(triangleGraph.nodes, node171);
	triangleGraph.nodes = append(triangleGraph.nodes, node171a);
	triangleGraph.nodes = append(triangleGraph.nodes, node171b);
	triangleGraph.nodes = append(triangleGraph.nodes, node172);
	triangleGraph.nodes = append(triangleGraph.nodes, node172a);
	triangleGraph.nodes = append(triangleGraph.nodes, node172b);
	triangleGraph.nodes = append(triangleGraph.nodes, node173);
	triangleGraph.nodes = append(triangleGraph.nodes, node173a);
	triangleGraph.nodes = append(triangleGraph.nodes, node173b);
	triangleGraph.nodes = append(triangleGraph.nodes, node174);
	triangleGraph.nodes = append(triangleGraph.nodes, node174a);
	triangleGraph.nodes = append(triangleGraph.nodes, node174b);
	triangleGraph.nodes = append(triangleGraph.nodes, node175);
	triangleGraph.nodes = append(triangleGraph.nodes, node175a);
	triangleGraph.nodes = append(triangleGraph.nodes, node175b);
	triangleGraph.nodes = append(triangleGraph.nodes, node176);
	triangleGraph.nodes = append(triangleGraph.nodes, node176a);
	triangleGraph.nodes = append(triangleGraph.nodes, node176b);
	triangleGraph.nodes = append(triangleGraph.nodes, node177);
	triangleGraph.nodes = append(triangleGraph.nodes, node177a);
	triangleGraph.nodes = append(triangleGraph.nodes, node177b);
	triangleGraph.nodes = append(triangleGraph.nodes, node178);
	triangleGraph.nodes = append(triangleGraph.nodes, node178a);
	triangleGraph.nodes = append(triangleGraph.nodes, node178b);
	triangleGraph.nodes = append(triangleGraph.nodes, node179);
	triangleGraph.nodes = append(triangleGraph.nodes, node179a);
	triangleGraph.nodes = append(triangleGraph.nodes, node179b);
	triangleGraph.nodes = append(triangleGraph.nodes, node180);
	triangleGraph.nodes = append(triangleGraph.nodes, node180a);
	triangleGraph.nodes = append(triangleGraph.nodes, node180b);
	triangleGraph.nodes = append(triangleGraph.nodes, node181);
	triangleGraph.nodes = append(triangleGraph.nodes, node181a);
	triangleGraph.nodes = append(triangleGraph.nodes, node181b);
	triangleGraph.nodes = append(triangleGraph.nodes, node182);
	triangleGraph.nodes = append(triangleGraph.nodes, node182a);
	triangleGraph.nodes = append(triangleGraph.nodes, node182b);
	triangleGraph.nodes = append(triangleGraph.nodes, node183);
	triangleGraph.nodes = append(triangleGraph.nodes, node183a);
	triangleGraph.nodes = append(triangleGraph.nodes, node183b);
	triangleGraph.nodes = append(triangleGraph.nodes, node184);
	triangleGraph.nodes = append(triangleGraph.nodes, node184a);
	triangleGraph.nodes = append(triangleGraph.nodes, node184b);
	triangleGraph.nodes = append(triangleGraph.nodes, node185);
	triangleGraph.nodes = append(triangleGraph.nodes, node185a);
	triangleGraph.nodes = append(triangleGraph.nodes, node185b);
	triangleGraph.nodes = append(triangleGraph.nodes, node186);
	triangleGraph.nodes = append(triangleGraph.nodes, node186a);
	triangleGraph.nodes = append(triangleGraph.nodes, node186b);
	triangleGraph.nodes = append(triangleGraph.nodes, node187);
	triangleGraph.nodes = append(triangleGraph.nodes, node187a);
	triangleGraph.nodes = append(triangleGraph.nodes, node187b);
	triangleGraph.nodes = append(triangleGraph.nodes, node188);
	triangleGraph.nodes = append(triangleGraph.nodes, node188a);
	triangleGraph.nodes = append(triangleGraph.nodes, node188b);
	triangleGraph.nodes = append(triangleGraph.nodes, node189);
	triangleGraph.nodes = append(triangleGraph.nodes, node189a);
	triangleGraph.nodes = append(triangleGraph.nodes, node189b);
	triangleGraph.nodes = append(triangleGraph.nodes, node190);
	triangleGraph.nodes = append(triangleGraph.nodes, node190a);
	triangleGraph.nodes = append(triangleGraph.nodes, node190b);
	triangleGraph.nodes = append(triangleGraph.nodes, node191);
	triangleGraph.nodes = append(triangleGraph.nodes, node191a);
	triangleGraph.nodes = append(triangleGraph.nodes, node191b);
	triangleGraph.nodes = append(triangleGraph.nodes, node192);
	triangleGraph.nodes = append(triangleGraph.nodes, node192a);
	triangleGraph.nodes = append(triangleGraph.nodes, node192b);
	triangleGraph.nodes = append(triangleGraph.nodes, node193);
	triangleGraph.nodes = append(triangleGraph.nodes, node193a);
	triangleGraph.nodes = append(triangleGraph.nodes, node193b);
	triangleGraph.nodes = append(triangleGraph.nodes, node194);
	triangleGraph.nodes = append(triangleGraph.nodes, node194a);
	triangleGraph.nodes = append(triangleGraph.nodes, node194b);
	triangleGraph.nodes = append(triangleGraph.nodes, node195);
	triangleGraph.nodes = append(triangleGraph.nodes, node195a);
	triangleGraph.nodes = append(triangleGraph.nodes, node195b);
	triangleGraph.nodes = append(triangleGraph.nodes, node196);
	triangleGraph.nodes = append(triangleGraph.nodes, node196a);
	triangleGraph.nodes = append(triangleGraph.nodes, node196b);
	triangleGraph.nodes = append(triangleGraph.nodes, node197);
	triangleGraph.nodes = append(triangleGraph.nodes, node197a);
	triangleGraph.nodes = append(triangleGraph.nodes, node197b);
	triangleGraph.nodes = append(triangleGraph.nodes, node198);
	triangleGraph.nodes = append(triangleGraph.nodes, node198a);
	triangleGraph.nodes = append(triangleGraph.nodes, node198b);
	triangleGraph.nodes = append(triangleGraph.nodes, node199);
	triangleGraph.nodes = append(triangleGraph.nodes, node199a);
	triangleGraph.nodes = append(triangleGraph.nodes, node199b);
	print(twoColorable(triangleGraph));
	
}
